"""Feature schema for the LTR ranker.

Phase 4 ships a Python-only feature implementation. The list below is the
single source of truth for *both* training-row construction and (eventually)
Go inference. When Phase 5 adds Go serving, the same names are codegen'd
into Go accessors so the feature vector indices line up at compile time.

Sources:
  RETRIEVAL       — from the impression's retrieval_scores blob
  STATIC_PRODUCT  — from products / OpenSearch _source
  PRODUCT_AGG     — from product_features (Beta-smoothed CTR, etc.)
  INTERACTION     — pure function of (query, product, ...); see transforms.py
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Source(str, Enum):
    RETRIEVAL = "retrieval"
    STATIC_PRODUCT = "static_product"
    PRODUCT_AGG = "product_agg"
    INTERACTION = "interaction"
    ONLINE_USER = "online_user"


@dataclass(frozen=True)
class FeatureDef:
    name: str
    source: Source
    description: str


# Ordered feature list. Append-only; do not reorder, ever.
#
# Phase 6 adds user_brand_affinity (ONLINE_USER). v1 still omits
# ctr_prior / purchase_rate: they smuggle position bias from the
# synthetic click stream into a non-IPS-weighted model — Phase 7
# brings them back with proper IPS correction.
FEATURES: tuple[FeatureDef, ...] = (
    FeatureDef("bm25_score",            Source.RETRIEVAL,      "BM25 raw score"),
    FeatureDef("bm25_rank",             Source.RETRIEVAL,      "BM25 rank within query (1-indexed); 0 if not in BM25 set"),
    FeatureDef("knn_score",             Source.RETRIEVAL,      "k-NN cosine similarity"),
    FeatureDef("knn_rank",              Source.RETRIEVAL,      "k-NN rank within query (1-indexed); 0 if not in k-NN set"),
    FeatureDef("rrf_score",             Source.RETRIEVAL,      "RRF fused score"),
    FeatureDef("popularity_prior",      Source.STATIC_PRODUCT, "Pre-existing popularity prior in [0,1]"),
    FeatureDef("price_log_cents",       Source.STATIC_PRODUCT, "log1p(price_cents)"),
    FeatureDef("title_length_tokens",   Source.STATIC_PRODUCT, "Token count of title"),
    FeatureDef("query_length_tokens",   Source.INTERACTION,    "Token count of query"),
    FeatureDef("query_has_brand",       Source.INTERACTION,    "Query contains a known brand token (0/1)"),
    FeatureDef("query_has_color",       Source.INTERACTION,    "Query contains a known color token (0/1)"),
    FeatureDef("query_has_size_pattern", Source.INTERACTION,   r"Query matches \b\d+(?:\.\d+)?\s?(oz|ml|gb|tb|in|cm|mm|kg|lb)\b (0/1)"),
    FeatureDef("user_brand_affinity",   Source.ONLINE_USER,    "User's click-share for the candidate's brand in [0,1]; 0 if unknown user"),
    FeatureDef("query_gender_intent",   Source.INTERACTION,    "Requested gender inferred from query: 0=none, 1=men, 2=women, 3=boys, 4=girls"),
    FeatureDef("product_gender",        Source.STATIC_PRODUCT, "Product gender inferred from category path: 0=none, 1=men, 2=women, 3=boys, 4=girls"),
    FeatureDef("gender_intent_match",   Source.INTERACTION,    "1 when query_gender_intent is known and equals product_gender"),
    FeatureDef("gender_intent_mismatch", Source.INTERACTION,   "1 when query_gender_intent and product_gender are known but differ"),
)

FEATURE_NAMES: tuple[str, ...] = tuple(f.name for f in FEATURES)
NUM_FEATURES: int = len(FEATURES)

# Drift guard: every import compares this hand-written list against the file
# generated by libs/schema/codegen.py from feature_schema.json (the canonical
# source of truth). If you see this assertion fail, run `make
# check-feature-parity` and reconcile.
from . import _generated as _gen  # noqa: E402

assert FEATURE_NAMES == _gen.FEATURE_NAMES, (
    f"feature schema drift: hand-written {FEATURE_NAMES} vs generated {_gen.FEATURE_NAMES}"
)
assert NUM_FEATURES == _gen.NUM_FEATURES
